### ISSUE TITLE
服务器设置失败

### ISSUE THREAD

**Issue by sherkwast** [pipesocks/pipesocks.github.io#18]
我用的搬瓦工的服务器
走到screen ./pipesocks pump -p 7473 -k key 这步时无法成功 
basic shell显示需要连接到一个终端
interactive shell敲完后进入黑屏
然后使用客户端不成功

**Comment by yvbbrjdr** [comment]
试试看
```bash
nohup ./pipesocks pump -p 7473 -k key &
```
（注意不要忘了最后的`&`）
然后敲两下回车
如果没有错误信息的话，pipesocks 应该就是跑在后台了。你再试试连接。如果不行的话看看防火墙。

**Comment by sherkwast** [comment]
[root@host home]# nohup ./pipesocks pump -p 7473 -k key &
[1] 3776
[root@host home]# nohup: ignoring input and appending output to `nohup.out
[1]+  Exit 126                nohup ./pipesocks pump -p 7473 -k key

依旧不成功，我看看防火墙吧

**Comment by yvbbrjdr** [comment]
这似乎是一个运行错误。你试试`cat nohup.out`应该能打印出错误。
