### ISSUE TITLE
Not support for mobile phones

### ISSUE THREAD

**Issue by yvbbrjdr** [pipesocks/pipesocks.github.io#2]

**Comment by D31F43** [comment]
It would be done after PC structure is fixed. (Btw, I don't think use small pic is a good choice, maybe to use a func to fit the pic? Whatever.
And would you prefer both mobile and PC use the same frame, or responsive frame?

**Comment by yvbbrjdr** [comment]
@NHibiki Same, I think. And 256*256 is definitely enough! It works pretty well on my retina screen.

**Comment by bdbai** [comment]
IMHO responsive design can be simply implemented using `viewport` meta attribute, Flex layout and css breakpoint. Properly sizing images is part of responsive design.
