### ISSUE TITLE
Some content addition and changes

### ISSUE THREAD

**Issue by yvbbrjdr** [pipesocks/pipesocks.github.io#3]
1. New download link has been generated, and could be added to Download section
pipesocks-2.2-linux.zip: https://coding.net/u/yvbbrjdr/p/pipesocks-release/git/raw/master/pipesocks-2.2-linux.zip
pipesocks-2.2-macOS.dmg: https://coding.net/u/yvbbrjdr/p/pipesocks-release/git/raw/master/pipesocks-2.2-macOS.dmg
pipesocks-2.2-win.exe: https://coding.net/u/yvbbrjdr/p/pipesocks-release/git/raw/master/pipesocks-2.2-win.exe

2. Remove the donate section since this project is illegal and any donation is illegal.

3. Add a tutorial section, both English and Chinese.

**Comment by D31F43** [comment]
QwQ... I did not see it.
Update next time.

**Comment by yvbbrjdr** [comment]
@NHibiki That's alright

**Comment by D31F43** [comment]
@yvbbrjdr 🙃

**Comment by bdbai** [comment]
How do we build a tutorial section? Writing HTML directly or using a generator to convert Markdown to HTML?

**Comment by D31F43** [comment]
@bdbai I prefer the later one. Dynamic is the best. ( Or maybe using the tool like pydoc?

**Comment by yvbbrjdr** [comment]
@NHibiki GitHub Pages itself supports Markdown interpreter, which converts Markdown to HTML. I would like to use 2 links (English and Mandarin) to directly route the page to 2 Markdown tutorial files in these different languages.
