### ISSUE TITLE
The font of some words falls back

### ISSUE THREAD

**Issue by yvbbrjdr** [pipesocks/pipesocks.github.io#9]
![img_0477](https://cloud.githubusercontent.com/assets/8556301/23097584/06253378-f672-11e6-8f3c-7ce3aec7a126.PNG)

Like this big pipesocks. It's not Roboto.

**Comment by bdbai** [comment]
Btw what does About section look like on your iPad? Portrait and landscape.

**Comment by D31F43** [comment]
@bdbai one issue. The nav will disappear when switch from portrait of small-width device to landscape ( check CSS media part ( I remember I had avoided that issue

**Comment by bdbai** [comment]
@NHibiki How wide is your screen?
In the last commit, the nav menu button never appears even when the browser window is in the width of its minimal, nor does my phones.

**Comment by D31F43** [comment]
@bdbai 噗 i mean when changing the phone rotation. The layout has some problem ( iPhone 7 Plus, WebKit

**Comment by yvbbrjdr** [comment]
@NHibiki There's another thing. The download table looks strange on small-width screen.

**Comment by bdbai** [comment]
@NHibiki 噗 I've fixed this lol
